### ISSUE TITLE
Feature: User can search for a stock

### ISSUE THREAD

**Issue by tychiang922** [tychiang922/ajax-project#1]
## ⚙️ Feature
User can search through a database of all stocks

## 📐 Functionality
User will be able to type the stock symbol they are searching for and will be recommended 5 stocks close to the search term as user types.

## 🖼️ Wireframes
<img width="343" alt="image" src="https://user-images.githubusercontent.com/103610490/174129371-40a32c92-9ec2-4ee3-aa9a-7fca6748509d.png">
<img width="338" alt="image" src="https://user-images.githubusercontent.com/103610490/174129399-49a175e4-6f0f-410a-b02c-9cb25979bbf0.png">
<img width="507" alt="image" src="https://user-images.githubusercontent.com/103610490/174129468-e4355ea0-bb12-4de5-834e-72cd470474a5.png">

## ✅ Task List
- [x] Create a base html/css framework for the home page
- [x] Create a search modal for when user presses on the text input box
- [x] Add event listeners for when user presses enter or when user blurs from the text input
- [x] Add function to submit the search value and request it from the API
