### ISSUE TITLE
Feature: User can view the current quote for a searched stock

### ISSUE THREAD

**Issue by tychiang922** [tychiang922/ajax-project#2]
## ⚙️ Feature
User will be able to view all current day quote information of a searched stock

## 📐 Functionality
User can view a graph of the price action of the selected stock for the last week and view all other basic quote data on one page.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/103610490/173681802-3cace639-a99b-43de-9fc6-3c4e2dfb4e2c.png)
![image](https://user-images.githubusercontent.com/103610490/173681841-aa5ba4fd-ef9b-4a35-90d9-6447c23bba7b.png)
![image](https://user-images.githubusercontent.com/103610490/173681892-855ef546-caac-44e9-9eb7-5c9518a91b89.png)
![image](https://user-images.githubusercontent.com/103610490/173681936-2867f6a9-534c-4f92-9e4c-3deef0e516f0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Setup a basic framework of HTML/CSS for the quotes page
- [x] Have a data-view attribute for the current pages it on
- [x] DOM creation on javascript for the entire page using data object pulled from API
- [x] Use chart.js library to graph price action of stock over the last 7 days and append to the dom
- [x] Record current search object info onto a property in data that will hold last 5 recent searches
- [x] Have those 5 recent searches append to the dom whenever submit occurs
