### ISSUE TITLE
Feature: User can add entries to a list

### ISSUE THREAD

**Issue by tychiang922** [tychiang922/ajax-project#3]
## ⚙️ Feature
User can bookmark an entry to a list

## 📐 Functionality
User can click the save button and save the current stock data to bookmarked list

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/103610490/173682600-0014009d-f554-4d00-877f-cd05443b972b.png)
![image](https://user-images.githubusercontent.com/103610490/173682631-18c75366-4348-495e-bf63-aa62d6981286.png)
![image](https://user-images.githubusercontent.com/103610490/173682662-abbbf086-167c-4dfc-bd63-c6c6bf16702c.png)
![image](https://user-images.githubusercontent.com/103610490/173682353-25d2e81b-f65a-4525-898b-c97333ed5fa3.png)
![image](https://user-images.githubusercontent.com/103610490/173682407-f67006c7-d876-4be7-bc78-6a900e94b8ee.png)
![image](https://user-images.githubusercontent.com/103610490/173682468-787308b2-03ea-4aca-80dd-909065289e8a.png)
![image](https://user-images.githubusercontent.com/103610490/173682548-59cd0dd5-de32-4658-81eb-2de6f11aea10.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create HTML/CSS for Save button
- [ ] Create a new property in Data object to store saved stock info
- [ ] Generate a function that triggers when Save button is clicked and will store current page info to the new property and will append symbol of stock to the bookmarked area
- [ ] Add an event listener to the generated bookmarks so when clicked, will display the info to the page
- [ ] Check for compatibility with mobile and desktop versions
